services:
  db:
    image: postgres:15.4-alpine
    container_name: feira_ciencias_db
    environment:
      POSTGRES_USER: feira_user
      POSTGRES_PASSWORD: feira_pass
      POSTGRES_DB: feira_ciencias
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feira_user -d feira_ciencias"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    container_name: localstack_s3
    image: localstack/localstack:3.4.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - ACTIVATE_PRO=false

  adminer:
    image: adminer
    container_name: feira_ciencias_adminer
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  app-dev:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: feira_ciencias_app_dev
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven_cache:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - QUARKUS_PROFILE=dev
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/feira_ciencias
      - QUARKUS_DATASOURCE_USERNAME=feira_user
      - QUARKUS_DATASOURCE_PASSWORD=feira_pass
      - STORAGE_S3_ENDPOINT=http://localstack:4566
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_ANALYTICS_DISABLED=true
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_started
    command: ["bash", "-lc", "mvn -pl bootstrap -am quarkus:dev -DdebugHost=0.0.0.0"]

volumes:
  postgres_data:
  pgadmin_data:
  maven_cache: